name: 'Create Stencil Store Archive Upload'
description: 'compresses and uploads an archive to be reused across jobs'
inputs:
  paths:
    description: 'paths to files or directories to archive (recursive)'
  output:
    description: 'output file name'
  name:
    description: 'name of the archive to upload'
runs:
  using: 'composite'
  steps:
    - name: Create Archive
      run: zip -q -r ${{ inputs.output }} ${{ inputs.paths }}
      shell: bash

    - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.output }}
