name: 'Stencil Store Archive Download'
description: 'downloads and decompresses an archive from a previous job'
inputs:
  path:
    description: 'location to decompress the archive to'
  filename:
    description: 'the name of the decompressed artifact'
  name:
    description: 'name of the archive to decompress'
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@9c19ed7fe5d278cd354c7dfd5d3b88589c7e2395 # v4.1.6
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - name: Extract Archive
      run: unzip -q -o ${{ inputs.path }}/${{ inputs.filename }}
      shell: bash
